# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='cart_price',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='related_cart',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='name',
            new_name='cart_item_name',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='cart_item_quantity',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='total',
            new_name='cart_item_total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='all_cart_item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='timmestamp',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_active',
            field=models.BooleanField(default=False),
        ),
    ]
