# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('carts', '0002_auto_20170831_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_date', models.DateTimeField(default=datetime.datetime(2017, 10, 8, 11, 59, 59, 132877, tzinfo=utc))),
                ('user', models.ManyToManyField(to='profiles.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Order'),
        ),
    ]
