# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20170908_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='max_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 8, 12, 4, 38, 610720, tzinfo=utc)),
        ),
    ]
